<?php

namespace FraisBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * FicheFraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheFraisRepository extends EntityRepository
{
    public function AllExceptLast($user) {


        $iduser = $user->getId();
        $request = $this
            ->createQueryBuilder('e')
            ->andWhere('e.user ='. $iduser)
            ->andWhere('e.monthyear <>\''. date('M - Y').'\'')
            //->orderBy('e.created', 'DESC')
            ->getQuery()
            ->getResult()
            ;
        return $request;
    }

    public function getFraisByDate($user)
    {
        $userId = $user->getId();
        $request = $this->createQueryBuilder('ff')
            ->where('ff.user ='. $userId )
            ->orderBy('ff.created', 'DESC')
            ->getQuery()
            ->execute()
        ;
        return $request;
    }

  public function getLastEntity($user) {
    $iduser = $user->getId();
    return $this
        ->createQueryBuilder('e')
        ->andWhere('e.user ='. $iduser)
        ->orderBy('e.created', 'DESC')
        ->setMaxResults(1)
        ->getQuery()
        ->getResult()
    ;
  }
}
