<?php

namespace FraisBundle\Repository;

/**
 * ForfaitHorsFraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForfaitHorsFraisRepository extends \Doctrine\ORM\EntityRepository
{
}
