<?php

namespace FraisBundle\Repository;

/**
 * ForfaitFraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForfaitFraisRepository extends \Doctrine\ORM\EntityRepository
{
}
