<?php

namespace FraisBundle\Repository;

/**
 * ForfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForfaitRepository extends \Doctrine\ORM\EntityRepository
{
}
