frais:
    resource: "@FraisBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /utilisateur


# login:
    # path: /login
  #  defaults:
   #     _controller: UserBundle:Security:login

#login_check:
 #   path: /login_check

#logout:
#    path: /logout

#ROUTE FOS USER BUNDLE
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#ROUTE API REST
#users:
#    type:     rest
#    resource: UserBundle\Controller\UserController

fichesFrais:
    type:     rest
    resource: FraisBundle\Controller\FicheFraisController

auth-tokens:
    type:     rest
    resource: UserBundle\Controller\AuthTokenController

