# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
     #   auth_token_user_provider:
      #              id: auth_token_user_provider
        main:
            id: fos_user.user_provider.username
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            #simple_preauth:
             #   authenticator: auth_token_authenticator
            #provider: auth_token_user_provider
            anonymous: true
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~


            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                success_handler: applifrais_login_success_handler
                failure_path:   null
            logout:
                path:       fos_user_security_logout
                target:     /
            remember_me:
                secret: %secret%

    encoders:
        UserBundle\Entity\User: sha512
        #algorithm: bcrypt
        #             cost: 12



    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_VISITEUR: ROLE_USER
        ROLE_COMPTABLE: ROLE_USER
        ROLE_ADMIN: ROLE_COMPTABLE
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_COMPTABLE, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


