# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    applifrais_login_success_handler:
        class:  UserBundle\Authentication\Authentication
        arguments:  ['@router', '@security.authorization_checker']
        tags:
            - { name: 'monolog.logger', channel: 'security' }
