fichefrais_index:
    path:     /
    defaults: { _controller: "FraisBundle:FicheFrais:index" }
    methods:  GET

index_admin:
    path:     /indexadmin
    defaults: { _controller: "FraisBundle:FicheFrais:indexAdmin" }
    methods:  GET

index_super_admin:
    path:     /indexsuperadmin
    defaults: { _controller: "FraisBundle:FicheFrais:indexSuperAdmin" }
    methods:  GET

fiche_par_user:
    path: /fichesdelutilisateur/{id}
    defaults: { _controller: "FraisBundle:FicheFrais:ficheParUser" }
    methods:  [GET, POST]

fichefrais_pdf:
    path:     /{id}/pdf
    defaults: { _controller: "FraisBundle:FicheFrais:pdf" }
    methods:  GET


fichefrais_show:
    path:     /{id}/show
    defaults: { _controller: "FraisBundle:FicheFrais:show" }
    methods:  GET

fichefrais_new:
    path:     /new
    defaults: { _controller: "FraisBundle:FicheFrais:new" }
    methods:  [GET, POST]

fichefrais_edit:
    path:     /{id}/edit
    defaults: { _controller: "FraisBundle:FicheFrais:edit" }
    methods:  [GET, POST]

fichefrais_etat:
    path:     /{id}/etat
    defaults: { _controller: "FraisBundle:FicheFrais:etat" }
    methods:  [GET, POST]

fichefrais_addForfaitFrais:
    path:     /{id}/addForfaitFrais
    defaults: { _controller: "FraisBundle:FicheFrais:addForfaitFrais" }
    methods:  [GET, POST]

fichefrais_delete:
    path:     /{id}/delete
    defaults: { _controller: "FraisBundle:FicheFrais:delete" }
    methods:  DELETE