services:
#    frais.example:
#        class: FraisBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    indexAction:
        class: AppliFrais\FraisBundle\Controller\ForfaitHorsFrais